const CLIENTS_NAME = {
  AUTH_SERVIC: 'AUTH_CLIENT',
  USER_SERVICE: 'USER_CLIENT',
  MESSAGE_SEND_RMQ_SERVICE: 'MESSAGE_SEND_RMQ_CLIENT',
  MESSAGE_VIEW_RMQ_SERVICE: 'MESSAGE_VIEW_RMQ_CLIENT',
};

export default CLIENTS_NAME;
